name: UpdateStrings 
on: 
  schedule:
    - cron: '0 12 * * 1-5' #  At 12:00 on day-of-week
  workflow_dispatch:
jobs:
  fetch:
    runs-on: ubuntu-latest
#    container:
#        image: debian
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
      - run: ls -l 
      - run: npm install
      - run: node bot.js
